version: '3.7'
services:
    # backend:
    #     container_name: backend
    #     build: ./backend
    #     env_file:
    #         - ./backend/.env
    #     volumes:
    #         - ./backend:/app
    #     ports:
    #         - '8000:8000'
    #     depends_on:
    #         - db
    #     command: python manage.py runserver 0.0.0.0:8000
    frontend:
        container_name: frontend
        build: ./frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - '8080:8080'
        # depends_on:
        #     - backend
        command: npm run serve
#     db:
#         container_name: db
#         image: postgres:12.1
#         volumes:
#             - database:/var/lib/postgresql/data/
#         environment:
#             - POSTGRES_USER=backend
#             - POSTGRES_PASSWORD=ea+QHLdw*e0rs7F9
#             - POSTGRES_DB=backend
#         ports:
#             - '5432:5432'
# volumes:
#     database: